version: '3'
services:
  devapp:
    container_name: devapp_container
    image: devapp
    restart: always
    build:
      context: .
      dockerfile: buildOne.Dockerfile

  prodapp:
    container_name: prodapp_container
    image: prodapp
    restart: always
    build:
      context: .
      dockerfile: buildTwo.Dockerfile
